---
apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: nginx-daemonset
  labels:
    author: intelliqit
spec:
  selector:
    matchLabels:
      author: intelliqit
  template:
    metadata:
      name: nginx-pod
      labels:
        author: intelliqit
    spec:
      containers:
        - name: mynginx
          image: nginx
...