---
apiVersion: v1
kind: Pod
metadata:
  name: ghost-pod
  namespace: test-ns
  labels:
    type: CMS
    author: intelliqit
spec:
  containers:
    - name: ghost
      image: ghost
      env:
        - name: NODE_ENV
          value: testing
...
