---
apiVersion: v1
kind: Pod
metadata:
  name: httpd-pod
  labels:
    author: intelliqit
spec:
  containers:
    - name: myhttpd
      image: httpd
  tolerations:
    - key: slave1
      operator: Equal
      value: intelliqit1
      effect: NoSchedule
...