---
apiVersion: v1
kind: pod
metadata: 
   name: jenkins-pod
   labels: 
     author: intelliqit 
     type: ci-cd
spec:
   containers: 
        - name: myjenkins
          image: jenkins/jenkins
          ports: 
            - container port: 8080
              host port: 9090  

...
          
                
               
                    
                    
                           
                                  
                          
                                        
                                            
                                         
                                     
                               
                             
                        
                  
                 

